included:
  - LibTrack

excluded:
  - Pods

line_length:
    warning: 300
    error: 700
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

disabled_rules:
  - force_cast
  - identifier_name

